name: release

on:
  push:
    tags:
    - "v[0-9]+.*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        CGO_ENABLED: 0
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
    - name: Build with CGO disabled for Alpine Linux
      run: |
        go get -v -t -d ./...
        mkdir out
        CGO_ENABLED=0 go build -a -installsuffix cgo -o ./out/terratag/terratag
    - name: Upload linux build
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://github.com/env0/terratag/releases/tag/${{ github.event.payload.ref.replace('refs/tags/', '') }}
        asset_path: ./out/terratag/terratag
        asset_name: terratag_${{ github.event.payload.ref.replace('refs/tags/', '') }}_linux_amd64.tar.gz
        asset_content_type: application/zip
